require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
ENV['RCT_NEW_ARCH_ENABLED'] = '1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'JsiBridge2Example' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'JsiBridge2ExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      next unless target.name == "fmt" || target.name == "react-native-jsi-bridge-2"

      target.build_configurations.each do |config|
        if target.name == "fmt"
          config.build_settings["CLANG_CXX_LANGUAGE_STANDARD"] = "c++17"
        else
          config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] = "$(inherited) RCT_NEW_ARCH_ENABLED=1"
          config.build_settings["OTHER_CPLUSPLUSFLAGS"] = "$(inherited) -DRCT_NEW_ARCH_ENABLED=1"
        end
      end
    end
end
end
